apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-basic-170408704
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/vysmeyvs-tenant/test-app-170408704/python-basic-170408704@sha256:08fc91031d1308472ba497f9759bc0043ab21212e0f9738cee64cca4ef734053
        name: my-python
        resources: {}
status: {}
